spring:
  jpa:
    # check sended query
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # run data.sql after create data table
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  security:
      oauth2:
        client:
          registration:
            google:
              client-id: 6353..
              client-secret: GOCS..
              scope:
                - email
                - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot
